---
title: "Focus Area Maps"
output:
  distill::distill_article:
    toc: false
    theme: theme.css
---
DallasCRED Violence Interrupters Focus Area maps generated by the Child Poverty Action Lab of Dallas

To navigate to your specified focus area, use the navigation bar in the upper right hand corner of the page and hover your mouse over the **Focus Area** section.

```{r, set-up block, include = FALSE}
library(tidyverse)
library(janitor)
library(rio)
library(tidygeocoder)
library(sf)
library(CPALtools)
library(leaflet)
library(leaflet.extras)
library(mapboxapi)
library(htmltools)
library(arcgisbinding)
library(lubridate)
library(kableExtra)

libDB <- "E:/CPAL Dropbox/"
libGH <- "C:/Michael Lopez/Documents/GitHub/violence-interrupters/"

YAPdir <- paste0(libDB, "Data Library/YAP/Dallas CRED/")

# Violent Incidents or Incident Responses
ViolentFiles <- list.files(path = paste0(YAPdir, "Incident Responses/"), pattern = "*.xlsx", full.names = TRUE)

Violentdf <- plyr::ldply(ViolentFiles, import) %>%
  clean_names(.)

ViolentClean <- Violentdf %>%
  filter(!str_detect(how_did_you_hear_about_shooting, "Follow")) %>%
  mutate(timeDiff = difftime(date_of_response, date_of_shooting_or_violent_incident, units = "days")) %>%
  geocode(address = address_or_intersection_of_shooting_violence_response,
          method = "arcgis") %>%
  filter(!is.na(lat)) %>%
  st_as_sf(coords = c("long", "lat"), crs = 4269) %>%
  st_join(., CRED_locations) %>%
  mutate(Location = ifelse(is.na(NAME), "Outside of Focus Area", NAME))

# Community Events
EventFiles <- list.files(path = paste0(YAPdir, "Community Events/"), pattern = "*.xlsx", full.names = TRUE)

Eventdf <- plyr::ldply(EventFiles, import) %>%
  clean_names(.)

EventClean <- Eventdf %>%
  geocode(address = address_of_community_event,
          method = "arcgis") %>%
  filter(!is.na(lat)) %>%
  st_as_sf(coords = c("long", "lat"), crs = 4269) %>%
  st_join(., CRED_locations) %>%
  mutate(Location = ifelse(is.na(NAME), "Outside of Focus Area", NAME))

#### Load CRED Locations #####
CRED_locations <- st_read(here::here("data/CRED_FocusAreas.geojson")) %>%
  select(-Shape_Leng, -Shape_Area) %>%
  st_zm() %>%
  st_transform(crs = 4269)

CRED_FA_LJM <- CRED_locations %>%
  filter(NAME == "Loop12_JimMiller")

CRED_FA_WCL <- CRED_locations %>%
  filter(NAME == "WebbChapel_Lombardy")

CRED_FA_CWG <- CRED_locations %>%
  filter(NAME == "CampWisdom_Gannon")

CRED_FA_OI <- CRED_locations %>%
  filter(NAME == "Overton_Illinois")

CRED_names <- data.frame(Order = c("1", "2", "3", "4"), FocusArea = c("Loop 12 and Jim Miller", 
                                                                      "Webb Chapel and Lombardy", 
                                                                      "Camp Wisdom and Gannon", 
                                                                      "Overton and Illinois"))

ViolentRec <- ViolentClean %>%
  st_drop_geometry(.) %>%
  filter(date_of_shooting_or_violent_incident >= max(date_of_shooting_or_violent_incident)-weeks(2)) %>%
  group_by(Location) %>%
  summarize(Incidents_2Weeks = n(),
            RecResTime = round(mean(timeDiff), digits = 1))

ViolentAll <- ViolentClean %>%
  st_drop_geometry(.) %>%
  group_by(Location) %>%
  summarize(Incidents_All = n(),
            AvgResTime = round(mean(timeDiff), digits = 1))


ViolentTbl <- left_join(ViolentAll, ViolentRec)

EventRec <- EventClean %>%
  st_drop_geometry(.) %>%
  filter(todays_date >= max(todays_date)-weeks(2)) %>%
  group_by(Location) %>%
  summarize(Incidents_2Weeks = n())

EventAll <- EventClean %>%
  st_drop_geometry(.) %>%
  group_by(Location) %>%
  summarize(Incidents_All = n())

EventTbl <- left_join(EventAll, EventRec)

```

```{r, Shooting Incident Table, echo = FALSE}
ViolentTbl %>%
  knitr::kable(.,
               col.names = c('Location', 'Incidents All Time', 'Average Response Time', 'Recent Incidents', 'Recent Response Time')) %>%
  kable_styling()
```

```{r, Community Events Table, echo = FALSE}
EventTbl %>%
  knitr::kable(.,
               col.names = c('Location', 'Events All Time', 'Recent Events')) %>%
  kable_styling()
```